[general]
static=yes
writeprotect=no
autofallthrough=yes

[globals]
AGENT_SCRIPT=agent.py

[from-linphone]
exten => _.,1,NoOp(Inbound call to AGI script on extension ${EXTEN})
 same => n,Answer()
 same => n,AGI(${AGENT_SCRIPT})
 same => n,Hangup()

exten => s,1,NoOp(Inbound call on s extension)
 same => n,Answer()
 same => n,AGI(${AGENT_SCRIPT})
 same => n,Hangup()
