[general]
context=from-linphone
bindport=5060
bindaddr=0.0.0.0
tcpenable=no
udpbindaddr=0.0.0.0
transport=udp
allowguest=no
srvlookup=yes
disallow=all
allow=ulaw,alaw
nat=force_rport,comedia
directmedia=no

; Linphone account settings:
; username: agent
; password: 1234
; host/domain: YOUR_LAPTOP_IP
[agent]
type=friend
host=dynamic
secret=1234
context=from-linphone
canreinvite=no
disallow=all
allow=ulaw,alaw
qualify=yes
nat=force_rport,comedia
